globalValues:
  valuesFile: values.yaml
  helmDefault: false
  spec:
    prune: true
    ref:
      branch: main
    interval: 30s

applications:
  Guestbook:
    repoURL: https://github.com/n-barnes/app-of-apps
    disable: false
    name: guestbook
    helm: false
    targetNamespace: argocd-guestbook
    path: ./guestbook
    branch: main

  helm-Guestbook:
    repoURL: https://n-barnes.github.io/app-of-apps/
    disable: false
    name: helm-guestbook
    helm: true
    targetNamespace: flux-system
    chart: helm-guestbook
    chartVersion: 0.1.0
    branch: main


